/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/contact': RouteRecordInfo<'/contact', '/contact', Record<never, never>, Record<never, never>>,
    '/help': RouteRecordInfo<'/help', '/help', Record<never, never>, Record<never, never>>,
    '/planner': RouteRecordInfo<'/planner', '/planner', Record<never, never>, Record<never, never>>,
    '/public-recipe': RouteRecordInfo<'/public-recipe', '/public-recipe', Record<never, never>, Record<never, never>>,
    '/recipe': RouteRecordInfo<'/recipe', '/recipe', Record<never, never>, Record<never, never>>,
    '/recipes': RouteRecordInfo<'/recipes', '/recipes', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
    '/tracker': RouteRecordInfo<'/tracker', '/tracker', Record<never, never>, Record<never, never>>,
    '/training': RouteRecordInfo<'/training', '/training', Record<never, never>, Record<never, never>>,
    '/trainingPlans': RouteRecordInfo<'/trainingPlans', '/trainingPlans', Record<never, never>, Record<never, never>>,
  }
}
