name: murmli
description: "A new Flutter project."

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.9.2

dependencies:
  # Flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Routing
  auto_route: ^10.1.2

  # State Management
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^3.0.3
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1

  # Data Classes
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # API
  retrofit: ^4.7.3
  envied: ^1.3.1
  dio: ^5.7.0
  native_dio_adapter: ^1.5.0

  # File handling
  file_picker: ^10.3.3
  share_plus: ^12.0.0
  cross_file: ^0.3.4+1
  path_provider: ^2.1.4
  permission_handler: ^12.0.1

  # Internationalization
  slang: ^4.9.0
  slang_flutter: ^4.9.0

  # Toast
  toastification: ^3.0.3

  # Storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  
  # Utilities
  uuid: ^4.5.1
  connectivity_plus: ^6.1.1
  package_rename_plus: ^1.11.0
  icons_launcher: ^3.0.3

dev_dependencies:
  # Testing
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter

  # Linting
  lintorium: ^38.1.0
  custom_lint: ^0.8.0

  # Routing
  auto_route_generator: ^10.2.4

  # State Management
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

  # Data Classes
  freezed: ^3.2.3
  json_serializable: ^6.11.1

  # API
  retrofit_generator: ^10.0.0
  envied_generator: ^1.3.1

  # Internationalization
  slang_build_runner: ^4.9.0

flutter:
  uses-material-design: true
