# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

frontend_dir = File.expand_path('../..')

platform :ios do
  lane :build do
    increment_build_number(
        xcodeproj: File.join(frontend_dir, 'ios/App/App.xcodeproj'),
        build_number: ENV["BUILD_NUMBER"]
    )

    build_app(
      workspace: File.join(frontend_dir, 'ios/App/App.xcworkspace'),
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.boundfoxstudios.murmli" => "Murmli Distribution"
        }
      },
      output_directory: File.join(frontend_dir, 'dist/iOS'),
      output_name: 'Murmli.ipa'
    )
  end

  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["APPLE_APP_STORE_KEY_ID"],
      issuer_id: ENV["APPLE_APP_STORE_KEY_ISSUER_ID"],
      key_content: ENV["APPLE_APP_STORE_CONNECT_KEY"],
      is_key_content_base64: true
    )

    upload_to_testflight(
      ipa: File.join(frontend_dir, 'dist/iOS/Murmli.ipa')
    )
  end
end
