name: Deploy to Azure murmli.de

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-node

      - name: Install backend dependencies (production)
        working-directory: ./backend
        run: npm ci --omit=dev

      - name: Zip artifact for deployment (backend only)
        working-directory: ./backend
        run: zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_373AC3D36CC8489C99145C0C1615AF9E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6108DED9499E4724AE434CCE597017F5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_79A8E13CDDD74F4D89D3B55E237B071D }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'murmli'
          slot-name: 'Production'
          package: release.zip
